image: cirrusci/flutter:3.5.3


stages:
  - analyze
  - test
  - build
  - deploy

cache:
  paths:
    - .pub-cache/

before_script:
  - flutter pub get

analyze:
  stage: analyze
  script:
    - flutter analyze

test:
  stage: test
  script:
    - flutter test

# build:
#   stage: build
#   script:
#     - flutter build apk --release
#   artifacts:
#     paths:
#       - build/app/outputs/flutter-apk/app-release.apk$

# deploy:
#   stage: deploy
#   only:
#     - main
#   script:
#     - echo "Déploiement en cours..."
