stages:
  - test
  - build

variables:
  FLUTTER_VERSION: "3.5.3" 

before_script:
  - apt-get update && apt-get install -y curl git unzip xz-utils zip libglu1-mesa openjdk-11-jdk
  - curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz | tar xJ
  - export PATH="$PATH:$CI_PROJECT_DIR/flutter/bin"
  - git config --global --add safe.directory /builds/leagrave/equipro/flutter
  - flutter doctor
  - dart pub cache repair

test_job:
  stage: test
  script:
    - flutter pub get
    - flutter test
  artifacts:
    paths:
      - coverage/

build_job:
  stage: build
  script:
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
