image: cirrusci/flutter:stable


stages:
  - analyze
  - test
  - build
  - deploy

before_script:
  - flutter doctor
  - flutter pub get

# analyze:
#   stage: analyze
#   script:
#     - flutter pub get
#     - flutter analyze

test:
  stage: test
  script:
    - flutter test

# build:
#   stage: build
#   script:
#     - flutter build apk --release
#   artifacts:
#     paths:
#       - build/app/outputs/flutter-apk/app-release.apk$

# deploy:
#   stage: deploy
#   only:
#     - main
#   script:
#     - echo "Déploiement en cours..."
