stages:
  - test
  - build

variables:
  FLUTTER_VERSION: "3.13.0" # Remplacez par la version que vous utilisez

before_script:
  - apt-get update && apt-get install -y curl git unzip xz-utils zip libglu1-mesa
  - curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz | tar xJ
  - export PATH="$PATH:$CI_PROJECT_DIR/flutter/bin"
  - flutter doctor

test_job:
  stage: test
  script:
    - flutter pub get
    - flutter test
  artifacts:
    paths:
      - coverage/ # Si vous générez un rapport de couverture

build_job:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
