stages:
  - build
  - test
  - deploy

# Job de build
build:
  stage: build
  image: cirrusci/flutter:latest  # Utilise une image Docker contenant Flutter
  script:
    - flutter pub get   # Télécharge les dépendances
    - flutter build apk # Génère l'APK pour Android (ou autre plateforme)
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/*.apk  # Sauvegarde l'APK généré pour le job suivant

# Job de tests
test:
  stage: test
  image: cirrusci/flutter:latest
  script:
    - flutter test # Exécute les tests unitaires

# Job de déploiement
deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours" # Ici tu peux mettre ton script de déploiement
  only:
    - master # Ne déploie que sur la branche master
