// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJujsK_ujwDcW48jBXyP9ecBYGp68PrEQ',
    appId: '1:706095522218:web:66d53a4dd6ca2b3f284bd3',
    messagingSenderId: '706095522218',
    projectId: 'equipro-messagerie',
    authDomain: 'equipro-messagerie.firebaseapp.com',
    storageBucket: 'equipro-messagerie.firebasestorage.app',
    measurementId: 'G-2922XS9CNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwCnfsHw5yRE9Pho0xIG_Iy9RjGC-p7aM',
    appId: '1:706095522218:android:c02b528a04f41cbd284bd3',
    messagingSenderId: '706095522218',
    projectId: 'equipro-messagerie',
    storageBucket: 'equipro-messagerie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyQ7_IlP2R_208r-TQMz9gcluBiSWTGmw',
    appId: '1:706095522218:ios:0ec4257269e21d04284bd3',
    messagingSenderId: '706095522218',
    projectId: 'equipro-messagerie',
    storageBucket: 'equipro-messagerie.firebasestorage.app',
    iosBundleId: 'com.lg.equipro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyQ7_IlP2R_208r-TQMz9gcluBiSWTGmw',
    appId: '1:706095522218:ios:0ec4257269e21d04284bd3',
    messagingSenderId: '706095522218',
    projectId: 'equipro-messagerie',
    storageBucket: 'equipro-messagerie.firebasestorage.app',
    iosBundleId: 'com.lg.equipro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJujsK_ujwDcW48jBXyP9ecBYGp68PrEQ',
    appId: '1:706095522218:web:b543758237e9e88f284bd3',
    messagingSenderId: '706095522218',
    projectId: 'equipro-messagerie',
    authDomain: 'equipro-messagerie.firebaseapp.com',
    storageBucket: 'equipro-messagerie.firebasestorage.app',
    measurementId: 'G-XXJNNG4K45',
  );
}
