name: CI_CD_Flutter_Render

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      version:
        description: 'New Release'
        required: false
        default: ''
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  setup_flutter:
    name: Setup Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

  flutter_analyze_test:
    name: Analyze & Test
    runs-on: ubuntu-latest
    needs: setup_flutter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze code
      #   run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test test/integration_test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  bump_version:
    name: Bump Flutter version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Récupérer la version actuelle
      - name: Get current version
        run: |
          current_version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)
          echo "current_version=$current_version" >> $GITHUB_ENV
          echo "Current version: $current_version"

      # Incrémenter la version
      - name: Bump version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.current_version }}"
          case "${{ github.event.inputs.version }}" in
            patch)
              patch=$((patch + 1))
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            *)
              echo "No version bump type provided. Using patch by default."
              patch=$((patch + 1))
              ;;
          esac
          new_version="$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "New version: $new_version"

      # Mettre à jour le pubspec.yaml
      - name: Update pubspec.yaml
        run: |
          sed -i "s/^version: .*/version: ${{ env.new_version }}+1/" pubspec.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pubspec.yaml
          git commit -m "Bump version to ${{ env.new_version }}"
          git push


  build_app:
    name: Build Flutter App
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release
      - if: runner.os == 'macOS'
        run: flutter build ios --release

  deploy_render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Trigger deployment on Render"
          curl -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            https://api.render.com/deploy/srv-$RENDER_SERVICE_ID
