name: CI_CD_Flutter_Render

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      version:
        description: 'New Release'
        required: false
        default: ''
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  flutter_pipeline:
    name: Flutter CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'
          channel: 'stable'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --coverage

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Build APK
        run: flutter build apk --release

      - name: Build iOS (macOS only)
        if: runner.os == 'macOS'
        run: flutter build ios --release

      # - name: Deploy to Render
      #   env:
      #     RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      #   run: |
      #     echo "Trigger deployment on Render"
      #     curl -X POST \
      #       -H "Accept: application/json" \
      #       -H "Authorization: Bearer $RENDER_API_KEY" \
      #       -H "Content-Type: application/json" \
      #       https://api.render.com/deploy/srv-$RENDER_SERVICE_ID
